### ISSUE TITLE
Score computation

### ISSUE THREAD

**Issue by ping** [danmolloy/spelling-bee#1]
I don't know if it's intentional that this version does not calculate word scores in the same way as the original, but I just wanted to report it just in case.

Original:
<img width="172" alt="site" src="https://github.com/danmolloy/spelling-bee/assets/104607/94b2a92e-b544-464e-8199-527a6e9a9aa1">

Replica:
<img width="172" alt="site" src="https://github.com/danmolloy/spelling-bee/assets/104607/a282e5dd-fb9c-4458-aff1-df5b9e152aa1">

In any case, only 6 points for a 9-letter word seems kinda harsh 😄

**Comment by danmolloy** [comment]
Hi Ping,

Thanks very much for alerting me to this, I've now corrected the error. It was due to my own misinterpretation of the NYT score count.

Thanks for taking an interest in my project!

Cheers, Dan
